# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a93b78f39cae4893de6b43e2bd0108d9"
name = "bank-transfer-extension"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
