name = "bank-transfer-extension"
client_id = "a93b78f39cae4893de6b43e2bd0108d9"
oauth_scopes = "write_checkouts"
org = "adinahousehold"

[[webhooks]]
topics = ["checkout-completed"]
uri = "/api/webhooks/checkout-completed"